### PR TITLE
feat: quasar config blog article

### PR DESCRIPTION
**Pull request by ayusham001**
/claim #42

### CODE REVIEW

**Comment by ayusham001** [comment]
@riderx, hava a look at it.

**Comment by riderx** [comment]
Hey @ayusham001 thanks a lot for the work ! I just merged another article, but i like the quality of your as well, i will tip you, can you update your Pr to upgrade the merged article with your images ?
( and can you convert them to webp ?)

**Comment by ayusham001** [comment]
> Hey @ayusham001 thanks a lot for the work ! I just merged another article, but i like the quality of your as well, i will tip you, can you update your Pr to upgrade the merged article with your images ? ( and can you convert them to webp ?)

Yaa sure.

**Comment by ayusham001** [comment]
Thank you @riderx .

**Comment by ayusham001** [comment]
Hi @riderx I have updated the article with the images
have a look at it.

**Pull request merged**
