### PR TITLE
Feat: Option to filter out the Blog topics

### LINKED ISSUE #127: Feat: Option to filter out the Blog topics
As the Blog list is increasing it would better if there is an option to filter out the topic. I've seen that feature in many websites.

eg:-
Screenshot 2023-09-14 075648
Screenshot 2023-09-14 075557
Screenshot 2023-09-14 075519

we can filter out the using the tag.

### PR DESCRIPTION
**Pull request by anikdhabal**
fixes #127 
Result:-
Screenshot 2023-09-14 102922
Screenshot 2023-09-14 102847

loom video-
https://www.loom.com/share/48570451af17427ca993802d0fe56d97

### CODE REVIEW

**Comment by anikdhabal** [comment]
cc: @riderx

**Comment by riderx** [comment]
Thanks that super nice addition !

**Comment by anikdhabal** [comment]
> /tip 30

Thanks a lot 🙏.

**Pull request merged**
