### PR TITLE
feat: Add astro-font to optimize fonts on the website

### PR DESCRIPTION
**Pull request by rishi-raj-jain**

### CODE REVIEW

**Comment by rishi-raj-jain** [comment]
image

**Comment by rishi-raj-jain** [comment]
after: https://app.netlify.com/sites/capgo/deploys/657c55c6f84be50008499951 > performance > CLS 0 (no elements found!)

**Comment by rishi-raj-jain** [comment]
image

**Comment by riderx** [comment]
Why the time to interactive is so hight though ?

**Pull request merged**
