### PR TITLE
automatic i18n for the whole website

### PR DESCRIPTION
**Pull request by rishi-raj-jain**

### CODE REVIEW

**Comment by WcaleNieWolny** [comment]
@riderx Can you review this PR?

**Comment by rishi-raj-jain** [comment]
> @riderx Can you review this PR?

We are coordinating in DMs. Still a WIP.

**Comment by rishi-raj-jain** [comment]
Ready for your review, @riderx.

**Comment by riderx** [comment]
merged thanks for the huge work !

**Pull request merged**
