### PR TITLE
feat: Add Quasar config in Blog

### LINKED ISSUE #42: Write blog article about quasar config with capgo

### PR DESCRIPTION
**Pull request by anikdhabal**
Quasar config added in the Blog.
Screenshot 2023-09-15 000849
 fixes #42 
/claim #42

### CODE REVIEW

**Comment by anikdhabal** [comment]
cc: @riderx

**Comment by riderx** [comment]
Thanks for the PR it's very good blog article there just one important point missing, the blog should speak about capgo live update not capacitor one :)

**Comment by anikdhabal** [comment]
> Thanks for the PR it's very good blog article there just one important point missing, the blog should speak about capgo live update not capacitor one :) You can look in the blog there other article who speak about it

Thanks for your review🙏. I am going to fix that.

**Comment by anikdhabal** [comment]
@riderx updated

**Comment by anikdhabal** [comment]
@riderx can you review it once?

**Pull request merged**
